// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR4P9GMiemNenWUZNKVjhc36bp_yy_URI',
    appId: '1:283713143686:web:fbc84c835719ce8a5d2207',
    messagingSenderId: '283713143686',
    projectId: 'ecs2-41c50',
    authDomain: 'ecs2-41c50.firebaseapp.com',
    databaseURL: 'https://ecs2-41c50-default-rtdb.firebaseio.com',
    storageBucket: 'ecs2-41c50.appspot.com',
    measurementId: 'G-56754ZPELE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRAUBEzFqyzhCTsywgw1bat6ZyDJ0IgI0',
    appId: '1:283713143686:android:695a8ab14b7f12895d2207',
    messagingSenderId: '283713143686',
    projectId: 'ecs2-41c50',
    databaseURL: 'https://ecs2-41c50-default-rtdb.firebaseio.com',
    storageBucket: 'ecs2-41c50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ajZ04o6Lp7czmLu-77Z-mtq1bIiyk8Q',
    appId: '1:283713143686:ios:bc12793232b65ba55d2207',
    messagingSenderId: '283713143686',
    projectId: 'ecs2-41c50',
    databaseURL: 'https://ecs2-41c50-default-rtdb.firebaseio.com',
    storageBucket: 'ecs2-41c50.appspot.com',
    iosBundleId: 'com.example.ecsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ajZ04o6Lp7czmLu-77Z-mtq1bIiyk8Q',
    appId: '1:283713143686:ios:bc12793232b65ba55d2207',
    messagingSenderId: '283713143686',
    projectId: 'ecs2-41c50',
    databaseURL: 'https://ecs2-41c50-default-rtdb.firebaseio.com',
    storageBucket: 'ecs2-41c50.appspot.com',
    iosBundleId: 'com.example.ecsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR4P9GMiemNenWUZNKVjhc36bp_yy_URI',
    appId: '1:283713143686:web:6b00fe65cef0af965d2207',
    messagingSenderId: '283713143686',
    projectId: 'ecs2-41c50',
    authDomain: 'ecs2-41c50.firebaseapp.com',
    databaseURL: 'https://ecs2-41c50-default-rtdb.firebaseio.com',
    storageBucket: 'ecs2-41c50.appspot.com',
    measurementId: 'G-CKC52D6XPY',
  );
}
